PresentationLayer/App.xaml, PresentationLayer/MainWindow.xaml, PresentationLayer/MainWindow.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/packages.config
Se añadió la librería de material design para que todos los miembros del equipo puedan comenzar a realizar sus interfaces
de usuario
=> [release] Adición de librería para material design

DataPersistenceLayer/Repositories/UserRepository.cs, PresentationLayer/CoordinatorRegistry.xaml, PresentationLayer/CoordinatorRegistry.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/Validators/AccountValidator.cs, PresentationLayer/Validators/CoordinatorValidator.cs, PresentationLayer/Validators/UserFeedback.cs, PresentationLayer/Validators/UserValidator.cs, UnitTests/CoordinatorRegistryTestCase/CoordinatorRegistryTest.cs, UnitTests/CoordinatorRegistryTestCase/GreenTextBoxesTest.cs, UnitTests/CoordinatorRegistryTestCase/InformationValidationTest.cs, UnitTests/CoordinatorRegistryTestCase/RedTextBoxesTest.cs, UnitTests/UnitTests.csproj
Se creó la lógica de validación para que los campos se marquen en verde o rojo dependiendo de si son válidos o no.
=> [BR-RegisterCoordinator] chore(validation)

DataPersistenceLayer/Repositories/IResponsibleProjectRepository.cs, DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs, DataPersistenceLayer/UnitsOfWork/IUnitOfWork.cs, DataPersistenceLayer/UnitsOfWork/UnitOfWork.cs, PresentationLayer/DeleteResponsibleProject.xaml, PresentationLayer/DeleteResponsibleProject.xaml.cs, PresentationLayer/ListResponsibleProject.xaml, PresentationLayer/ListResponsibleProject.xaml.cs, PresentationLayer/ModifyResponsibleProject.xaml, PresentationLayer/ModifyResponsibleProject.xaml.cs, UnitTests/DataPersistenceLayerTests/ResponsibleProjectTest/ConsultResponsibleProjectTest.cs, UnitTests/DataPersistenceLayerTests/ResponsibleProjectTest/ResponsibleProjectTest.cs
Realización del la funcionalidad de consultar responsable del proyecto
=> Realización del la funcionalidad de consultar responsable del proyecto

PresentationLayer/App.xaml, PresentationLayer/CoordinatorDeletion.xaml, PresentationLayer/CoordinatorDeletion.xaml.cs, PresentationLayer/CoordinatorModification.xaml, PresentationLayer/CoordinatorModification.xaml.cs, PresentationLayer/CoordinatorRegistry.xaml, PresentationLayer/CoordinatorRegistry.xaml.cs, PresentationLayer/PresentationLayer.csproj, UnitTests/UnitTests.csproj
Se mejoró la interfaz de usuario del CRUD de coordinador.
=> [BR-UserInterfaceImprovement]

PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/PracticionerConsult.xaml.cs, PresentationLayer/PracticionerRegistry.xaml, PresentationLayer/PracticionerRegistry.xaml.cs, PresentationLayer/PresentationLayer.csproj
Unir los CU registrar y consultar con la ventana menú coordinador
=> [BR-PracticionerUserInterfaceImprovement]

PresentationLayer/ManagerMenu.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/TeacherConsultation.xaml, PresentationLayer/TeacherConsultation.xaml.cs, PresentationLayer/TeacherDeletion.xaml, PresentationLayer/TeacherDeletion.xaml.cs, UnitTests/DataPersistenceLayerTests/TeacherTest/ConsultTeacherTest.cs, UnitTests/UnitTests.csproj
Creación de la Funcionalidad consultar Profesor
=> Creación de la Funcionalidad consultar Profesor

PresentationLayer/PresentationLayer.csproj, PresentationLayer/TeacherDeletion.xaml, PresentationLayer/TeacherDeletion.xaml.cs, UnitTests/DataPersistenceLayerTests/TeacherTest/TeacherTest.cs, UnitTests/UnitTests.csproj
Creación de la funcionalidad Eliminar profesor
=> Creación de la funcionalidad Eliminar profesor

DataPersistenceLayer/DataPersistenceLayer.csproj, DataPersistenceLayer/Entities/State.cs, DataPersistenceLayer/Migrations/Configuration.cs, DataPersistenceLayer/Repositories/ILinkedOrganizationRepository.cs, DataPersistenceLayer/Repositories/IPhoneRepository.cs, DataPersistenceLayer/Repositories/LinkedOrganizationRepository.cs, DataPersistenceLayer/Repositories/PhoneRepository.cs, DataPersistenceLayer/UnitsOfWork/IUnitOfWork.cs, DataPersistenceLayer/UnitsOfWork/UnitOfWork.cs, PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/LinkedOrganizationModification.xaml, PresentationLayer/LinkedOrganizationModification.xaml.cs, PresentationLayer/LinkedOrganizationRegistry.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/Validators/LinkedOrganizationValidator.cs, UnitTests/LinkedOrganizationModificationTestCase/LinkedOrganizationModificationTest.cs, UnitTests/LinkedOrganizationModificationTestCase/PhoneTest.cs, UnitTests/UnitTests.csproj, UnitTests/ValidatorsTests/LinkedOrganizationValidatorTest.cs
feat: Se creó la funcionalidad de modificar una organización vinculada.
=> [BR-LinkedOrganizationModification]

PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/LinkedOrganizationConsultation.xaml, PresentationLayer/LinkedOrganizationConsultation.xaml.cs, PresentationLayer/LinkedOrganizationModification.xaml.cs, PresentationLayer/PresentationLayer.csproj
Creación de la funcionalidad de consultar organizaciones vinculadas
=> [BR-LinkedOrganizationConsultation]

PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/LinkedOrganizationModification.xaml.cs, PresentationLayer/LinkedOrganizationRegistry.xaml, PresentationLayer/LinkedOrganizationRegistry.xaml.cs, PresentationLayer/PresentationLayer.csproj
fix: Se arregló el problema con los code-behind de las funcionalidades de organización vinculada
=> [BR-FixCodeBehind]

DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs, PresentationLayer/Validators/ResponsibleProjectValidator.cs
Cambiar la validación del responsibleProject
=> Cambiar la validación del responsibleProject

DataPersistenceLayer/Repositories/ILinkedOrganizationRepository.cs, DataPersistenceLayer/Repositories/LinkedOrganizationRepository.cs, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/LinkedOrganizationConsultation.xaml.cs, PresentationLayer/LinkedOrganizationDeletion.xaml, PresentationLayer/LinkedOrganizationDeletion.xaml.cs, PresentationLayer/ManagerMenu.xaml, PresentationLayer/ManagerMenu.xaml.cs, PresentationLayer/PresentationLayer.csproj, UnitTests/LinkedOrganizationDeletionTestCase/LinkedOrganizationDeletionTest.cs, UnitTests/UnitTests.csproj
Se creó la funcionalidad para eliminar organizaciones vinculadas.
=> [BR-LinkedOrganizationDeletion]

DataPersistenceLayer/DataPersistenceLayer.csproj, DataPersistenceLayer/Entities/Project.cs, DataPersistenceLayer/Entities/SchedulingActivity.cs, DataPersistenceLayer/Migrations/202104021823238_UpdateProject.cs, DataPersistenceLayer/UnitsOfWork/IUnitOfWork.cs, DataPersistenceLayer/UnitsOfWork/UnitOfWork.cs, PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/LinkedOrganizationChoose.xaml, PresentationLayer/LinkedOrganizationChoose.xaml.cs, PresentationLayer/Login.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/ProjectRegistry.xaml, PresentationLayer/ProjectRegistry.xaml.cs, PresentationLayer/ResponsibleProjectChoose.xaml, PresentationLayer/ResponsibleProjectChoose.xaml.cs, PresentationLayer/Validators/ProjectValidator.cs, PresentationLayer/Validators/SchedulingActivityValidator.cs, UnitTests/DataPersistenceLayerTests/ProjectTest/LinkedOrganizationChooseTest.cs, UnitTests/DataPersistenceLayerTests/ProjectTest/ProjectRegistryTest.cs, UnitTests/DataPersistenceLayerTests/ProjectTest/ResponsibleProjectChooseTest.cs, UnitTests/DataPersistenceLayerTests/ProjectTest/SchedulingActivityTest.cs, UnitTests/UnitTests.csproj
Creación de la funcionalidad registrar proyecto
=> Creación de la funcionalidad registrar proyecto

PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/ProjectConsultation.xaml, PresentationLayer/ProjectConsultation.xaml.cs
feat: Creación de la funcionalidad para consultar proyectos
=> [BR-ProjectConsultation]

DataPersistenceLayer/Migrations/Configuration.cs, DataPersistenceLayer/UnitsOfWork/IUnitOfWork.cs, DataPersistenceLayer/UnitsOfWork/UnitOfWork.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/ProjectConsultation.xaml.cs, PresentationLayer/ProjectDeletion.xaml, PresentationLayer/ProjectDeletion.xaml.cs
feat: Creación de funcionalidad para eliminar a un proyecto.
Notas:
* Falta realización de pruebas unitarias.
* Falta arreglar algunos detalles sobre los datos mostrados en la UI.
=> [BR-ProjectDeletion]

DataPersistenceLayer/DataPersistenceLayer.csproj, PresentationLayer/PresentationLayer.csproj, PresentationLayer/ProjectConsultation.xaml.cs, PresentationLayer/ProjectModification.xaml, PresentationLayer/ProjectModification.xaml.cs, PresentationLayer/SchedulingActivityModification.xaml, PresentationLayer/SchedulingActivityModification.xaml.cs, PresentationLayer/SchedulingActivityRegistration.xaml, PresentationLayer/SchedulingActivityRegistration.xaml.cs, SPP.sln, UnitTests/DataPersistenceLayerTests/ProjectTest/ProjectModificationTest.cs, UnitTests/UnitTests.csproj
Creación de la funcionalidad Modificar proyecto
=> Creación de la funcionalidad Modificar proyecto

DataPersistenceLayer/Entities/Project.cs, PresentationLayer/ProjectRegistry.xaml.cs, PresentationLayer/Validators/ProjectValidator.cs, UnitTests/DataPersistenceLayerTests/ProjectTest/ProjectRegistryTest.cs
Agregar el campo DaysHours en la funcionalidad registrar proyecto
=> Agregar el campo DaysHours en la funcionalidad registrar proyecto

PresentationLayer/ProjectModification.xaml, PresentationLayer/ProjectModification.xaml.cs
Agregar Campo DaysHours a la funcionalidad Modificar proyecto
=> Agregar Campo DaysHours a la funcionalidad Modificar proyecto

DataPersistenceLayer/Repositories/IPracticionerRepository.cs, DataPersistenceLayer/Repositories/PracticionerRepository.cs, PresentationLayer/CoordinatorMenu.xaml.cs, PresentationLayer/CoordinatorRegistry.xaml.cs, PresentationLayer/PracticionerConsult.xaml.cs, PresentationLayer/PracticionerModification.xaml.cs, PresentationLayer/PracticionerRegistry.xaml.cs, UnitTests/PracticionerRegistryTestCase/PracticionerRegistryTest.cs
Fix errors consult practicioners
=> Fix errors consult practicioners

PresentationLayer/ActivityReportList.xaml, PresentationLayer/ActivityReportList.xaml.cs, PresentationLayer/Login.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/ReportEvaluation.xaml, PresentationLayer/ReportEvaluation.xaml.cs, PresentationLayer/TeacherMenu.xaml, PresentationLayer/TeacherMenu.xaml.cs, UnitTests/DataPersistenceLayerTests/ReportTest/ReportAddTest.cs, UnitTests/DataPersistenceLayerTests/ReportTest/ReportEvaluationTest.cs, UnitTests/UnitTests.csproj
Creación de la funcionalidad evaluar reportes
=> Creación de la funcionalidad evaluar reportes

PresentationLayer/CoordinatorMenu.xaml, PresentationLayer/Validators/ResponsibleProjectValidator.cs
Cambios en la validación del responsable del proyecto
=> Cambios en la validación del responsable del proyecto

PresentationLayer/PracticionerModification.xaml, PresentationLayer/PracticionerModification.xaml.cs
Quitar campo matrícula en Modificar practicante
=> Quitar campo matrícula en Modificar practicante

PresentationLayer/CoordinatorRegistry.xaml, PresentationLayer/PracticionerRegistry.xaml, PresentationLayer/TeacherRegistry.xaml, PresentationLayer/Validators/AccountValidator.cs, PresentationLayer/Validators/CoordinatorValidator.cs, PresentationLayer/Validators/UserValidator.cs
patch: Se agregaron etiquetas de guía para los usuarios en la vista de registro de coordinador
=> [BR-PatchUILabels]

PresentationLayer/CoordinatorMenu.xaml.cs
Integrar las precondiciones en los botones
=> Integrar las precondiciones en los botones 

DataPersistenceLayer/Repositories/ITeacherRepository.cs, DataPersistenceLayer/Repositories/TeacherRepository.cs, PresentationLayer/ManagerMenu.xaml.cs, PresentationLayer/PresentationLayer.csproj, PresentationLayer/TeacherConsultation.xaml.cs, PresentationLayer/TeacherModification.xaml, PresentationLayer/TeacherModification.xaml.cs, PresentationLayer/Validators/TeacherValidator.cs, UnitTests/TeacherModificationTestCase/TeacherModificationTest.cs, UnitTests/UnitTests.csproj
Añadir funcionalidad modificar profesor
=> BR-TeacherModification

PresentationLayer/ActivityReportList.xaml.cs, PresentationLayer/ReportEvaluation.xaml.cs, PresentationLayer/TeacherMenu.xaml.cs
Integración de la pre-condición en Evaluar reporte
=> Integración de la pre-condición en Evaluar reporte

PresentationLayer/PracticionerMenu.xaml.cs, PresentationLayer/ReportAdd.xaml.cs, PresentationLayer/ReportList.xaml.cs
Integración de pre-condición en Funcionalidad Añadir reporte
=> Integración de pre-condición en Funcionalidad Añadir reporte

Utilities/AssignmentOfficeTemplate.cs, Utilities/DocumentGenerator.cs
patch: se agregó el número de oficio en el oficio de asignación
=> [BR-AssignationOfficePatch]

DataPersistenceLayer/Repositories/ResponsibleProjectRepository.cs, PresentationLayer/PartialReportGeneration.xaml.cs
Corrección del repositorio del responsable del proyecto en el método si esta asignado el responsable
=> Corrección del repositorio del responsable del proyecto

PresentationLayer/ReportAdd.xaml.cs, PresentationLayer/ReportEvaluation.xaml.cs, Utilities/FileExplorer.cs
Corrección del método de descarga de documento en los casos de uso añadir reporte y evaluar reportes
=> Corrección del método de descarga de documento
